### ISSUE TITLE
[BUG] Error in executing `examples/pipeline_human_local_single.py`

### ISSUE THREAD

**Issue by nerdai** [run-llama/llama_deploy#101]
When trying to run the script `examples/pipeline_human_local_single.py`, I get this error:

```sh
  File "/Users/nerdai/Projects/llama-agents/llama_agents/orchestrators/pipeline.py", line 183, in get_next_messages
    queue_message = get_service_component_message(
  File "/Users/nerdai/Projects/llama-agents/llama_agents/orchestrators/pipeline.py", line 34, in get_service_component_message
    if module.module_type == ModuleType.AGENT:
AttributeError: 'RouterComponent' object has no attribute 'module_type'
```

**Comment by peteryxu** [comment]
ServiceComponent has the attribute of 'module_type', while RouterComponent does not have since it is NOT a  ServiceComponent. 

In the current examples/pipeline_human_local_single.py file, when creating QueryPipeline,  an RouterComponent was passed in, vs ServiceComponent.  

I did some testing, just commented out RouterCompoent, and pass in the two service components directly, and it seems to work in my local env and setup.


####################################
pipeline = QueryPipeline(
    chain=[
        agent_component,
        human_component
        # RouterComponent(
        #     selector=PydanticSingleSelector.from_defaults(llm=OpenAI()),
        #     choices=[agent_service.description, human_service.description],
        #     components=[agent_component, human_component],
        # )
    ]
)

**Comment by peteryxu** [comment]
Tested code above, and it worked as seen below. Created a PR #112 to merge. 

<img width="1026" alt="image" src="https://github.com/run-llama/llama-agents/assets/5605055/175767f5-c0f2-49ff-9546-97ac2aebce5c">
